import * as esbuild from 'esbuild';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

await esbuild.build({
  entryPoints: [join(__dirname, 'processes/stats-processor/index.ts')],
  bundle: true,
  platform: 'node',
  target: 'node24',
  format: 'cjs',
  outfile: join(__dirname, 'dist/stats-processor.js'),
  external: [
    'sqlite3',
    'bufferutil',
    '@napi-rs/canvas',
    'discord.js',
    '@discordjs/voice',
    '@discordjs/rest',
    '@discordjs/builders',
    '@discordjs/util',
    '@discordjs/ws',
    'fs', 'path', 'crypto', 'os', 'stream', 'http', 'https', 'net', 'tls', 'zlib', 'events', 'util',
  ],
  treeShaking: true,
  minify: true,
  sourcemap: false,
  logLevel: 'info',
  banner: {
    js: '// Stats Processor Bundle - Generated by esbuild\n// MatchExec Match Bot\n',
  },
});

console.log('✓ Stats processor bundled successfully');
