import * as esbuild from 'esbuild';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

await esbuild.build({
  entryPoints: [join(__dirname, 'processes/discord-bot/index.ts')],
  bundle: true,
  platform: 'node',
  target: 'node24',
  format: 'cjs',
  outfile: join(__dirname, 'dist/discord-bot.js'),
  external: [
    // Discord.js and related packages (large, native dependencies)
    'discord.js',
    '@discordjs/voice',
    '@discordjs/rest',
    '@discordjs/builders',
    '@discordjs/util',
    '@discordjs/ws',

    // Native modules
    'sqlite3',
    'bufferutil',

    // TTS library
    '@snazzah/davey',

    // Node.js built-ins (automatically external, but explicit for clarity)
    'fs',
    'path',
    'crypto',
    'os',
    'stream',
    'http',
    'https',
    'net',
    'tls',
    'zlib',
    'events',
    'util',
  ],
  treeShaking: true,
  minify: true,
  sourcemap: false,
  logLevel: 'info',
  banner: {
    js: '// Discord Bot Bundle - Generated by esbuild\n// MatchExec Match Bot\n',
  },
});

console.log('✓ Discord bot bundled successfully');
