import * as esbuild from 'esbuild';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

await esbuild.build({
  entryPoints: [join(__dirname, 'processes/scheduler/index.ts')],
  bundle: true,
  platform: 'node',
  target: 'node24',
  format: 'cjs',
  outfile: join(__dirname, 'dist/scheduler.js'),
  external: [
    // Native modules
    'sqlite3',

    // Cron library
    'node-cron',

    // Node.js built-ins (automatically external, but explicit for clarity)
    'fs',
    'path',
    'crypto',
    'os',
    'stream',
    'http',
    'https',
    'net',
    'tls',
    'zlib',
    'events',
    'util',
  ],
  treeShaking: true,
  minify: true,
  sourcemap: false,
  logLevel: 'info',
  banner: {
    js: '// Scheduler Bundle - Generated by esbuild\n// MatchExec Match Bot\n',
  },
});

console.log('✓ Scheduler bundled successfully');
