apiVersion: v2
name: matchexec
description: MatchExec Discord Match & Tournament Bot
type: application
version: 0.1.0
appVersion: "0.7.2"
keywords:
  - discord
  - gaming
  - matchmaking
  - tournament
home: https://matchexec.com
maintainers:
  - name: matchexec
