{{- if not .Values.existingSecret -}}
{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matchexec.fullname" . }}
  labels:
    {{- include "matchexec.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
