name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-latest
          - platform: arm64
            runner: ubuntu-24.04-arm
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/${{ matrix.platform }}
        push: true
        tags: ghcr.io/${{ github.actor }}/matchexec:dev-${{ matrix.platform }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Log in to GitHub Container Registry
      run: |
        echo ${{ secrets.GHCR_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin ghcr.io
        
    - name: Create and push manifest
      run: |
        docker buildx imagetools create -t ghcr.io/${{ github.actor }}/matchexec:dev \
          ghcr.io/${{ github.actor }}/matchexec:dev-amd64 \
          ghcr.io/${{ github.actor }}/matchexec:dev-arm64