name: Create Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip release]')"
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-latest
          - platform: arm64
            runner: ubuntu-24.04-arm
    outputs:
      version: ${{ steps.package_version.outputs.version }}
      tag_exists: ${{ steps.check_tag.outputs.exists }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        
    - name: Get package version
      id: package_version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
    - name: Check if tag exists
      id: check_tag
      run: |
        if git rev-parse "v${{ steps.package_version.outputs.version }}" >/dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Create Release
      if: steps.check_tag.outputs.exists == 'false'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.package_version.outputs.version }}
        release_name: Release v${{ steps.package_version.outputs.version }}
        body: |
          ## 🐛 Bug Fixes
          
          ## ✨ New Features

          ## 🎮 Game Data
          
          **Docker Image:** `ghcr.io/${{ github.actor }}/matchexec:v${{ steps.package_version.outputs.version }}`
        draft: true
        prerelease: false
        
    - name: Set up Docker Buildx
      if: steps.check_tag.outputs.exists == 'false'
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to GitHub Container Registry
      if: steps.check_tag.outputs.exists == 'false'
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin ghcr.io
        
    - name: Build and push production Docker image
      if: steps.check_tag.outputs.exists == 'false'
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/${{ matrix.platform }}
        push: true
        tags: |
          ghcr.io/${{ github.actor }}/matchexec:v${{ steps.package_version.outputs.version }}-${{ matrix.platform }}
          ghcr.io/${{ github.actor }}/matchexec:latest-${{ matrix.platform }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  release:
    if: "!contains(github.event.head_commit.message, '[skip release]')"
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      packages: write
      
    steps:
    - name: Log in to GitHub Container Registry
      if: needs.build.outputs.tag_exists == 'false'
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin ghcr.io
        
    - name: Create and push manifest
      if: needs.build.outputs.tag_exists == 'false'
      run: |
        docker buildx imagetools create -t ghcr.io/${{ github.actor }}/matchexec:v${{ needs.build.outputs.version }} \
          ghcr.io/${{ github.actor }}/matchexec:v${{ needs.build.outputs.version }}-amd64 \
          ghcr.io/${{ github.actor }}/matchexec:v${{ needs.build.outputs.version }}-arm64
        docker buildx imagetools create -t ghcr.io/${{ github.actor }}/matchexec:latest \
          ghcr.io/${{ github.actor }}/matchexec:latest-amd64 \
          ghcr.io/${{ github.actor }}/matchexec:latest-arm64
          
    - name: Create Release
      if: needs.build.outputs.tag_exists == 'false'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ needs.build.outputs.version }}
        release_name: Release v${{ needs.build.outputs.version }}
        body: |
          ## 🐛 Bug Fixes
          
          ## ✨ New Features

          ## 🎮 Game Data
          
          **Docker Image:** `ghcr.io/${{ github.actor }}/matchexec:v${{ needs.build.outputs.version }}`
        draft: true
        prerelease: false